name: annot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - argon2-cffi-bindings==25.1.0
      - datetime==5.5
      - debugpy==1.8.15
      - ipyannotations==0.5.1
      - ipycanvas==0.13.3
      - ipyevents==2.0.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.7
      - jsonpointer==3.0.0
      - jupyterlab-widgets==3.0.8
      - notebook==7.4.4
      - numpy==2.3.2
      - palettable==3.3.3
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - pillow==11.3.0
      - psutil==7.0.0
      - python-json-logger==3.3.0
      - pyzmq==27.0.0
      - rpds-py==0.26.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - voila==0.5.9
      - websockets==15.0.1
      - widgetsnbextension==4.0.14
      - zope-interface==7.2
